### ISSUE TITLE
Fix update process to allow missing municipalities

### ISSUE THREAD

**Issue by luopio** [kooditiimi/smbackend#3]
discovered during updates: 

```
Iltapäivätoiminta / Maunulan ala-aste, Opetustoimi (7349) created
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lauri/code/montel/smbackend/venv_smbackend/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/lauri/code/montel/smbackend/venv_smbackend/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lauri/code/montel/smbackend/venv_smbackend/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lauri/code/montel/smbackend/venv_smbackend/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/Users/lauri/code/montel/smbackend/venv_smbackend/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/lauri/code/montel/smbackend/services/management/commands/services_import.py", line 869, in handle
    method()
  File "/Users/lauri/code/montel/smbackend/services/management/commands/services_import.py", line 749, in import_units
    self._import_unit(syncher, info)
  File "/Users/lauri/.pyenv/versions/3.4.6/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/lauri/code/montel/smbackend/services/management/commands/services_import.py", line 443, in _import_unit
    muni = self.muni_by_name[muni_name]
KeyError: 'hämeenkoski'
```

**Comment by luopio** [comment]
fixed by ignoring the municipality in these cases
